version: "3"
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web/nginx.dev.conf:/etc/nginx/nginx.conf
    environment:
      - VIRTUAL_HOST=template.local 
      - VIRTUAL_PORT=8080
    links:
      - client
      - server
    networks:
      - proxynet
      - default
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
        - ./client:/app
    networks:
        - default
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
        - DB_HOST=db
        - DB_DATABASE=template
        - DB_USERNAME=template
        - DB_PASSWORD=template_db_password
    volumes:
      - ./server:/var/www
    links:
        - db:db
    networks:
      - default
      - proxynet
  db:
    image: mysql:5.7
    volumes:
      - database:/var/lib/mysql
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "template", "-ptemplate_db_password"]
        timeout: 20s
        retries: 10
    ports:
      - 7003:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_ROOT_USER=root 
      - MYSQL_DATABASE=template 
      - MYSQL_USER=template 
      - MYSQL_PASSWORD=template_db_password
    networks:
      - default
  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 9002:80
    environment:
      PMA_HOST: db
      PMA_USER: template
      PMA_PASSWORD: template_db_password

volumes:
  database:
    driver: local

networks:
  proxynet:
    external:
      name: proxy_network
  default:
