<template>
<div>
<svg 
    xmlns="http://www.w3.org/2000/svg" 
    xmlns:xlink="http://www.w3.org/1999/xlink" 
    style="margin: auto; display: block; shape-rendering: auto;" 
    :width="size + 'px'" 
    :height="size + 'px'" 
    viewBox="0 0 100 100" 
    preserveAspectRatio="xMidYMid">
<rect x="19" y="19" width="20" height="20" fill="#3c64b1">
  <animate attributeName="fill" values="#20c9ff;#3c64b1;#3c64b1" keyTimes="0;0.125;1" dur="0.9174311926605504s" repeatCount="indefinite" begin="0s" calcMode="discrete"></animate>
</rect><rect x="40" y="19" width="20" height="20" fill="#3c64b1">
  <animate attributeName="fill" values="#20c9ff;#3c64b1;#3c64b1" keyTimes="0;0.125;1" dur="0.9174311926605504s" repeatCount="indefinite" begin="0.1146788990825688s" calcMode="discrete"></animate>
</rect><rect x="61" y="19" width="20" height="20" fill="#3c64b1">
  <animate attributeName="fill" values="#20c9ff;#3c64b1;#3c64b1" keyTimes="0;0.125;1" dur="0.9174311926605504s" repeatCount="indefinite" begin="0.2293577981651376s" calcMode="discrete"></animate>
</rect><rect x="19" y="40" width="20" height="20" fill="#3c64b1">
  <animate attributeName="fill" values="#20c9ff;#3c64b1;#3c64b1" keyTimes="0;0.125;1" dur="0.9174311926605504s" repeatCount="indefinite" begin="0.8027522935779816s" calcMode="discrete"></animate>
</rect><rect x="61" y="40" width="20" height="20" fill="#3c64b1">
  <animate attributeName="fill" values="#20c9ff;#3c64b1;#3c64b1" keyTimes="0;0.125;1" dur="0.9174311926605504s" repeatCount="indefinite" begin="0.3440366972477064s" calcMode="discrete"></animate>
</rect><rect x="19" y="61" width="20" height="20" fill="#3c64b1">
  <animate attributeName="fill" values="#20c9ff;#3c64b1;#3c64b1" keyTimes="0;0.125;1" dur="0.9174311926605504s" repeatCount="indefinite" begin="0.6880733944954128s" calcMode="discrete"></animate>
</rect><rect x="40" y="61" width="20" height="20" fill="#3c64b1">
  <animate attributeName="fill" values="#20c9ff;#3c64b1;#3c64b1" keyTimes="0;0.125;1" dur="0.9174311926605504s" repeatCount="indefinite" begin="0.573394495412844s" calcMode="discrete"></animate>
</rect><rect x="61" y="61" width="20" height="20" fill="#3c64b1">
  <animate attributeName="fill" values="#20c9ff;#3c64b1;#3c64b1" keyTimes="0;0.125;1" dur="0.9174311926605504s" repeatCount="indefinite" begin="0.4587155963302752s" calcMode="discrete"></animate>
</rect>
<!-- [ldio] generated by https://loading.io/ --></svg>
</div>
</template>
<script>
export default {
    name: "Spinner",
    props: {
        size: {
            type: Number,
            default: 50,
            required: false
        }
    }
}
</script>